remotes:
  test1:
    buttons:
      volumeUp:
        signal: "100,200,300"
        action: 
          type: "mqtt"
          topic: "ir/test"
          payload: "{\"button\":\"volumeUp\"}"
      volumeDown:
        signal: "100,200,400"
  test2:
    buttons:
      channelUp:
        signal: "200,200,300"
      channelDown:
        signal: "200,200,400"
devices:
  - name: "test-device0"
    on_threshold_milliamps: 1000
  - name: "test-device1"
    on_threshold_milliamps: 2000
